title: Heiko Panjas
email: heiko@panjas.com
description: "Write an awesome description for your new site here"
url: "https://heikopanjas.github.io"

# Build settings
remote_theme: heikopanjas/rain-jekyll-theme
plugins:
  - jekyll-feed
  - jekyll-paginate

# Author
author:
  name: Heiko Panjas
  email: heiko@panjas.com
  url: https://panjas.com

# Links to social media
social:
  email: heiko@panjas.com
  github: https://github.com/heikopanjas
  mastodon: https://chaos.social/@joe_viterbo
  # linkedin: https://www.linkedin.com/in/heiko-panjas-440433253/

# Assets
sass:
  sass_dir: _sass
  style: compressed

# Permalinks
permalink: /:year-:month-:day/:title
paginate: 5

# Related posts settings
related_posts_section:
  max_count: 5
  min_common_tags: 2
