title: Heiko Panjas
email: heiko@panjas.com
description: "Software development and consulting."
url: "https://heikopanjas.github.io"

# Build settings
remote_theme: heikopanjas/rain-jekyll-theme
plugins:
  - jekyll-feed
  - jekyll-paginate

# Author
author:
  name: Heiko Panjas
  email: heiko@panjas.com
  url: https://panjas.com

# Links to social media
social:
  email: heiko@panjas.com
  github: https://github.com/heikopanjas
  mastodon: https://chaos.social/@joe_viterbo
  rss: https://panjas.com/feed.xml

# Links to legal pages
legal:
  imprint: /imprint
  privacy: /privacy

# That's me
introduction: true

# Assets
sass:
  sass_dir: _sass
  style: compressed

# Permalinks
permalink: /blog/:year-:month-:day/:title
paginate: 15

# Related posts settings
related_posts_section:
  max_count: 5
  min_common_tags: 2
